### ISSUE TITLE
Network Calls are being executed on MAIN thread

### ISSUE THREAD

**Issue by rajitdeb** [PratikFagadiya/Agentpedia-ValorantEdition#1]
Network/IO calls should never be executed on MAIN thread as it may block the UI and even crash the app. Rather these network calls should only be executed on IO thread.

Requires attention - @PratikFagadiya

**Comment by rajitdeb** [comment]
Also label this issue as "good first issue" and "hacktoberfest"

**Comment by rajitdeb** [comment]
I can solve this issue. Please assign this issue to me @PratikFagadiya

**Comment by PratikFagadiya** [comment]
Thanks @rajitdeb 
I'm assigning this task to you @rajitdeb

**Comment by rajitdeb** [comment]
@PratikFagadiya Fixed the issue in PR #3. Please review the code and merge :)
