### ISSUE TITLE
Agent Skills Grid gets smaller for Astra agent

### ISSUE THREAD

**Issue by rajitdeb** [PratikFagadiya/Agentpedia-ValorantEdition#2]
All other agents have a fixed size for Skills grid in `Homescreen` but `Astra` has a 5 Skills which makes the grid size relatively small and inconsistent UI. See this:

| Expected Behaviour | Issue |
|--------|----------|
|[![1.jpg](https://i.postimg.cc/fWHZdmwN/1.jpg)](https://postimg.cc/3WDP5y4S)|[![2.jpg](https://i.postimg.cc/vTKpN7Bx/2.jpg)](https://postimg.cc/7JgsC2Sq)|

All the skills icon should be of fixed size (as shown in `Image 1`), if needed, give them a scroll behaviour to accomodate all the skills but with equal size.

Requires attention @PratikFagadiya

**Comment by PratikFagadiya** [comment]
@rajitdeb Thanks for submitting issue, Would you like to work on it ? Let me know so i can assign it to you.

**Comment by Pasqua101** [comment]
If @rajitdeb doesn't want to work on it, can I take a shot at it? @PratikFagadiya. I have some experience with Android Development with Java, but not with Kotlin. So I'm not sure how tough this will be for me, but I don't mind trying it out.

**Comment by rajitdeb** [comment]
@Pasqua101 Sorry bro i already started working on it. Forgot to remind @PratikFagadiya to assign me

**Comment by Pasqua101** [comment]
All good. Thanks for letting me know. Best of luck!

**Comment by rajitdeb** [comment]
Fixed Issue in PR (#4). Also take a look at [this comment](https://github.com/PratikFagadiya/Agentpedia-ValorantEdition/pull/4#issuecomment-1758077614) for the actual screen recording of the changes made and how it looks. @PratikFagadiya

**Comment by PratikFagadiya** [comment]
Thanks @Pasqua101 for showing interest. As you know this issue fixed by @rajitdeb but you can check other repo for it.
